"use client";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import ToastProvider from "@/components/ToastProvider";
import YandexMetrika from "@/components/yandexMetrika";
import ParticlesBackground from "@/components/ParticlesBackground";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <ToastProvider>
            <YandexMetrika />
            <ParticlesBackground />
            {children}
          </ToastProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
